/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SpotifyRouteImport } from './routes/spotify'
import { Route as NewRouteImport } from './routes/new'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as TIdResultsRouteImport } from './routes/t.$id.results'
import { Route as TIdPlayRouteImport } from './routes/t.$id.play'
import { Route as TIdJoinRouteImport } from './routes/t.$id.join'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyRoute = SpotifyRouteImport.update({
  id: '/spotify',
  path: '/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdResultsRoute = TIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TIdRoute,
} as any)
const TIdPlayRoute = TIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => TIdRoute,
} as any)
const TIdJoinRoute = TIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => TIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/spotify': typeof SpotifyRoute
  '/tournaments': typeof TournamentsRoute
  '/about': typeof AboutLazyRoute
  '/t/$id': typeof TIdRouteWithChildren
  '/t/$id/join': typeof TIdJoinRoute
  '/t/$id/play': typeof TIdPlayRoute
  '/t/$id/results': typeof TIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/spotify': typeof SpotifyRoute
  '/tournaments': typeof TournamentsRoute
  '/about': typeof AboutLazyRoute
  '/t/$id': typeof TIdRouteWithChildren
  '/t/$id/join': typeof TIdJoinRoute
  '/t/$id/play': typeof TIdPlayRoute
  '/t/$id/results': typeof TIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/spotify': typeof SpotifyRoute
  '/tournaments': typeof TournamentsRoute
  '/about': typeof AboutLazyRoute
  '/t/$id': typeof TIdRouteWithChildren
  '/t/$id/join': typeof TIdJoinRoute
  '/t/$id/play': typeof TIdPlayRoute
  '/t/$id/results': typeof TIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/new'
    | '/spotify'
    | '/tournaments'
    | '/about'
    | '/t/$id'
    | '/t/$id/join'
    | '/t/$id/play'
    | '/t/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/new'
    | '/spotify'
    | '/tournaments'
    | '/about'
    | '/t/$id'
    | '/t/$id/join'
    | '/t/$id/play'
    | '/t/$id/results'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new'
    | '/spotify'
    | '/tournaments'
    | '/about'
    | '/t/$id'
    | '/t/$id/join'
    | '/t/$id/play'
    | '/t/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  SpotifyRoute: typeof SpotifyRoute
  TournamentsRoute: typeof TournamentsRoute
  AboutLazyRoute: typeof AboutLazyRoute
  TIdRoute: typeof TIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify': {
      id: '/spotify'
      path: '/spotify'
      fullPath: '/spotify'
      preLoaderRoute: typeof SpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id/results': {
      id: '/t/$id/results'
      path: '/results'
      fullPath: '/t/$id/results'
      preLoaderRoute: typeof TIdResultsRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/play': {
      id: '/t/$id/play'
      path: '/play'
      fullPath: '/t/$id/play'
      preLoaderRoute: typeof TIdPlayRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/join': {
      id: '/t/$id/join'
      path: '/join'
      fullPath: '/t/$id/join'
      preLoaderRoute: typeof TIdJoinRouteImport
      parentRoute: typeof TIdRoute
    }
  }
}

interface TIdRouteChildren {
  TIdJoinRoute: typeof TIdJoinRoute
  TIdPlayRoute: typeof TIdPlayRoute
  TIdResultsRoute: typeof TIdResultsRoute
}

const TIdRouteChildren: TIdRouteChildren = {
  TIdJoinRoute: TIdJoinRoute,
  TIdPlayRoute: TIdPlayRoute,
  TIdResultsRoute: TIdResultsRoute,
}

const TIdRouteWithChildren = TIdRoute._addFileChildren(TIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  SpotifyRoute: SpotifyRoute,
  TournamentsRoute: TournamentsRoute,
  AboutLazyRoute: AboutLazyRoute,
  TIdRoute: TIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
